### ISSUE TITLE
Dockerfile todo list

### ISSUE THREAD

**Issue by certik** [sympy/planet-sympy#1]
* [x] Install all prerequisites and copy over the `planet` subdirectory in this repo and make sure it runs (see e.g. nbviewer's [Dockerfile](https://github.com/jupyter/nbviewer/blob/38efb5cd3e1ab5a5aa392d7dec06aabf33653991/Dockerfile) how to do that)
* [x] Install cron to run the update periodically (see e.g. [here](https://www.ekito.fr/people/run-a-cron-job-with-docker/) for instructions)
* [x] Add automatic push of the generated html pages into github from the cron job. This requires to have a github token, that will be passed to the docker image via an environment variable (as well as a git repository URL, also passed in as a variable). On Travis we pass in a token for a test repository that we just keep somewhere. In production (e.g. on Linode), we put in a token for the planet.sympy.org github repo.
* [ ] add a deploy key to Travis and push to a test repository in PRs/master, i.e. Travis never pushes into the production repository, but it will test that everything works as expected (#22)
* [ ] Setup automatic uploading of the final docker image to docker hub every time master changes (i.e. a PR gets merged). See [here](https://docs.docker.com/docker-hub/builds/) for instructions. (#23)

To test it on Travis, we just have to figure out how to trigger a cron job run, which will generate new html pages by aggregating the blogs for planet.sympy.org and pushes to the test repository. If any command fails, then Travis will fail. We'll probably simply examine the html pages in this test repository manually, because it's hard to write a good test for that, and if things get pushed, then it probably works.

People can then send PRs against this repository, e.g. when a new blog is added or removed, or some improvements of the design. Travis will then test the PR to make sure things work, if it passes, we merge the PR, which will trigger uploading the new docker image on docker hub. Then on our production server we simply switch to a new image. If, for some reason, the new image doesn't work in production, we simply revert to the old (working) image.

**Comment by certik** [comment]
The docker image is now running, it should update every 20 min.

**Comment by certik** [comment]
I created new issues for the missing things that are not yet implemented (#22, #23), so I am closing this one.
